// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: internal/infer/pb/task.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskName string `protobuf:"bytes,1,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"`
	Source   string `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_infer_pb_task_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infer_pb_task_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_internal_infer_pb_task_proto_rawDescGZIP(), []int{0}
}

func (x *TaskRequest) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *TaskRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type TaskResultSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*TaskResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *TaskResultSet) Reset() {
	*x = TaskResultSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_infer_pb_task_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskResultSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResultSet) ProtoMessage() {}

func (x *TaskResultSet) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infer_pb_task_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResultSet.ProtoReflect.Descriptor instead.
func (*TaskResultSet) Descriptor() ([]byte, []int) {
	return file_internal_infer_pb_task_proto_rawDescGZIP(), []int{1}
}

func (x *TaskResultSet) GetResults() []*TaskResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type TaskResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClassId    int32     `protobuf:"varint,1,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	Name       string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TrackId    int32     `protobuf:"varint,3,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	Confidence float64   `protobuf:"fixed64,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Box        *Box      `protobuf:"bytes,5,opt,name=box,proto3" json:"box,omitempty"`
	Segments   *Segments `protobuf:"bytes,6,opt,name=segments,proto3" json:"segments,omitempty"`
	Speed      *Speed    `protobuf:"bytes,7,opt,name=speed,proto3" json:"speed,omitempty"`
	Shape      []int32   `protobuf:"varint,8,rep,packed,name=shape,proto3" json:"shape,omitempty"`
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_infer_pb_task_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infer_pb_task_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_internal_infer_pb_task_proto_rawDescGZIP(), []int{2}
}

func (x *TaskResult) GetClassId() int32 {
	if x != nil {
		return x.ClassId
	}
	return 0
}

func (x *TaskResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TaskResult) GetTrackId() int32 {
	if x != nil {
		return x.TrackId
	}
	return 0
}

func (x *TaskResult) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *TaskResult) GetBox() *Box {
	if x != nil {
		return x.Box
	}
	return nil
}

func (x *TaskResult) GetSegments() *Segments {
	if x != nil {
		return x.Segments
	}
	return nil
}

func (x *TaskResult) GetSpeed() *Speed {
	if x != nil {
		return x.Speed
	}
	return nil
}

func (x *TaskResult) GetShape() []int32 {
	if x != nil {
		return x.Shape
	}
	return nil
}

type Box struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X1 float64 `protobuf:"fixed64,1,opt,name=x1,proto3" json:"x1,omitempty"`
	X2 float64 `protobuf:"fixed64,2,opt,name=x2,proto3" json:"x2,omitempty"`
	Y1 float64 `protobuf:"fixed64,3,opt,name=y1,proto3" json:"y1,omitempty"`
	Y2 float64 `protobuf:"fixed64,4,opt,name=y2,proto3" json:"y2,omitempty"`
	X3 float64 `protobuf:"fixed64,5,opt,name=x3,proto3" json:"x3,omitempty"`
	X4 float64 `protobuf:"fixed64,6,opt,name=x4,proto3" json:"x4,omitempty"`
	Y3 float64 `protobuf:"fixed64,7,opt,name=y3,proto3" json:"y3,omitempty"`
	Y4 float64 `protobuf:"fixed64,8,opt,name=y4,proto3" json:"y4,omitempty"`
}

func (x *Box) Reset() {
	*x = Box{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_infer_pb_task_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Box) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Box) ProtoMessage() {}

func (x *Box) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infer_pb_task_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Box.ProtoReflect.Descriptor instead.
func (*Box) Descriptor() ([]byte, []int) {
	return file_internal_infer_pb_task_proto_rawDescGZIP(), []int{3}
}

func (x *Box) GetX1() float64 {
	if x != nil {
		return x.X1
	}
	return 0
}

func (x *Box) GetX2() float64 {
	if x != nil {
		return x.X2
	}
	return 0
}

func (x *Box) GetY1() float64 {
	if x != nil {
		return x.Y1
	}
	return 0
}

func (x *Box) GetY2() float64 {
	if x != nil {
		return x.Y2
	}
	return 0
}

func (x *Box) GetX3() float64 {
	if x != nil {
		return x.X3
	}
	return 0
}

func (x *Box) GetX4() float64 {
	if x != nil {
		return x.X4
	}
	return 0
}

func (x *Box) GetY3() float64 {
	if x != nil {
		return x.Y3
	}
	return 0
}

func (x *Box) GetY4() float64 {
	if x != nil {
		return x.Y4
	}
	return 0
}

type Segments struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X []float64 `protobuf:"fixed64,1,rep,packed,name=x,proto3" json:"x,omitempty"`
	Y []float64 `protobuf:"fixed64,2,rep,packed,name=y,proto3" json:"y,omitempty"`
}

func (x *Segments) Reset() {
	*x = Segments{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_infer_pb_task_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Segments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Segments) ProtoMessage() {}

func (x *Segments) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infer_pb_task_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Segments.ProtoReflect.Descriptor instead.
func (*Segments) Descriptor() ([]byte, []int) {
	return file_internal_infer_pb_task_proto_rawDescGZIP(), []int{4}
}

func (x *Segments) GetX() []float64 {
	if x != nil {
		return x.X
	}
	return nil
}

func (x *Segments) GetY() []float64 {
	if x != nil {
		return x.Y
	}
	return nil
}

type Speed struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Inference   float64 `protobuf:"fixed64,1,opt,name=inference,proto3" json:"inference,omitempty"`
	Postprocess float64 `protobuf:"fixed64,2,opt,name=postprocess,proto3" json:"postprocess,omitempty"`
	Preprocess  float64 `protobuf:"fixed64,3,opt,name=preprocess,proto3" json:"preprocess,omitempty"`
}

func (x *Speed) Reset() {
	*x = Speed{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_infer_pb_task_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Speed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Speed) ProtoMessage() {}

func (x *Speed) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infer_pb_task_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Speed.ProtoReflect.Descriptor instead.
func (*Speed) Descriptor() ([]byte, []int) {
	return file_internal_infer_pb_task_proto_rawDescGZIP(), []int{5}
}

func (x *Speed) GetInference() float64 {
	if x != nil {
		return x.Inference
	}
	return 0
}

func (x *Speed) GetPostprocess() float64 {
	if x != nil {
		return x.Postprocess
	}
	return 0
}

func (x *Speed) GetPreprocess() float64 {
	if x != nil {
		return x.Preprocess
	}
	return 0
}

var File_internal_infer_pb_task_proto protoreflect.FileDescriptor

var file_internal_infer_pb_task_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x69, 0x6e, 0x66, 0x65, 0x72,
	0x2f, 0x70, 0x62, 0x2f, 0x74, 0x61, 0x73, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x42,
	0x0a, 0x0b, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a,
	0x09, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x74, 0x61, 0x73, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x22, 0x36, 0x0a, 0x0d, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x53, 0x65, 0x74, 0x12, 0x25, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x22, 0xe9, 0x01, 0x0a, 0x0a, 0x54,
	0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x6c, 0x61,
	0x73, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x63, 0x6c, 0x61,
	0x73, 0x73, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x72, 0x61, 0x63,
	0x6b, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x74, 0x72, 0x61, 0x63,
	0x6b, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x64, 0x65, 0x6e, 0x63,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x64, 0x65,
	0x6e, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x03, 0x62, 0x6f, 0x78, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x04, 0x2e, 0x42, 0x6f, 0x78, 0x52, 0x03, 0x62, 0x6f, 0x78, 0x12, 0x25, 0x0a, 0x08, 0x73,
	0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e,
	0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x08, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x12, 0x1c, 0x0a, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x06, 0x2e, 0x53, 0x70, 0x65, 0x65, 0x64, 0x52, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x73, 0x68, 0x61, 0x70, 0x65, 0x18, 0x08, 0x20, 0x03, 0x28, 0x05, 0x52,
	0x05, 0x73, 0x68, 0x61, 0x70, 0x65, 0x22, 0x85, 0x01, 0x0a, 0x03, 0x42, 0x6f, 0x78, 0x12, 0x0e,
	0x0a, 0x02, 0x78, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x02, 0x78, 0x31, 0x12, 0x0e,
	0x0a, 0x02, 0x78, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x02, 0x78, 0x32, 0x12, 0x0e,
	0x0a, 0x02, 0x79, 0x31, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x02, 0x79, 0x31, 0x12, 0x0e,
	0x0a, 0x02, 0x79, 0x32, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x02, 0x79, 0x32, 0x12, 0x0e,
	0x0a, 0x02, 0x78, 0x33, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x02, 0x78, 0x33, 0x12, 0x0e,
	0x0a, 0x02, 0x78, 0x34, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x02, 0x78, 0x34, 0x12, 0x0e,
	0x0a, 0x02, 0x79, 0x33, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52, 0x02, 0x79, 0x33, 0x12, 0x0e,
	0x0a, 0x02, 0x79, 0x34, 0x18, 0x08, 0x20, 0x01, 0x28, 0x01, 0x52, 0x02, 0x79, 0x34, 0x22, 0x26,
	0x0a, 0x08, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x01, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x01, 0x52, 0x01, 0x79, 0x22, 0x67, 0x0a, 0x05, 0x53, 0x70, 0x65, 0x65, 0x64, 0x12,
	0x1c, 0x0a, 0x09, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x09, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x70, 0x6f, 0x73, 0x74, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x0b, 0x70, 0x6f, 0x73, 0x74, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x12,
	0x1e, 0x0a, 0x0a, 0x70, 0x72, 0x65, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x0a, 0x70, 0x72, 0x65, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x32,
	0x3e, 0x0a, 0x0b, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2f,
	0x0a, 0x0d, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x12,
	0x0c, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e,
	0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x53, 0x65, 0x74, 0x30, 0x01, 0x42,
	0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x6d,
	0x61, 0x75, 0x72, 0x65, 0x72, 0x31, 0x39, 0x39, 0x34, 0x2f, 0x67, 0x6f, 0x66, 0x69, 0x73, 0x68,
	0x2d, 0x62, 0x6f, 0x74, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x69, 0x6e,
	0x66, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_infer_pb_task_proto_rawDescOnce sync.Once
	file_internal_infer_pb_task_proto_rawDescData = file_internal_infer_pb_task_proto_rawDesc
)

func file_internal_infer_pb_task_proto_rawDescGZIP() []byte {
	file_internal_infer_pb_task_proto_rawDescOnce.Do(func() {
		file_internal_infer_pb_task_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_infer_pb_task_proto_rawDescData)
	})
	return file_internal_infer_pb_task_proto_rawDescData
}

var file_internal_infer_pb_task_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_infer_pb_task_proto_goTypes = []any{
	(*TaskRequest)(nil),   // 0: TaskRequest
	(*TaskResultSet)(nil), // 1: TaskResultSet
	(*TaskResult)(nil),    // 2: TaskResult
	(*Box)(nil),           // 3: Box
	(*Segments)(nil),      // 4: Segments
	(*Speed)(nil),         // 5: Speed
}
var file_internal_infer_pb_task_proto_depIdxs = []int32{
	2, // 0: TaskResultSet.results:type_name -> TaskResult
	3, // 1: TaskResult.box:type_name -> Box
	4, // 2: TaskResult.segments:type_name -> Segments
	5, // 3: TaskResult.speed:type_name -> Speed
	0, // 4: TaskService.StreamResults:input_type -> TaskRequest
	1, // 5: TaskService.StreamResults:output_type -> TaskResultSet
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_internal_infer_pb_task_proto_init() }
func file_internal_infer_pb_task_proto_init() {
	if File_internal_infer_pb_task_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_infer_pb_task_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*TaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_infer_pb_task_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*TaskResultSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_infer_pb_task_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*TaskResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_infer_pb_task_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*Box); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_infer_pb_task_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*Segments); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_infer_pb_task_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*Speed); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_infer_pb_task_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_infer_pb_task_proto_goTypes,
		DependencyIndexes: file_internal_infer_pb_task_proto_depIdxs,
		MessageInfos:      file_internal_infer_pb_task_proto_msgTypes,
	}.Build()
	File_internal_infer_pb_task_proto = out.File
	file_internal_infer_pb_task_proto_rawDesc = nil
	file_internal_infer_pb_task_proto_goTypes = nil
	file_internal_infer_pb_task_proto_depIdxs = nil
}
