# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inferencetask.proto
# Protobuf Python Version: 5.28.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    0,
    '',
    'inferencetask.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13inferencetask.proto\"0\n\x0bTaskRequest\x12\x11\n\ttask_name\x18\x01 \x01(\t\x12\x0e\n\x06source\x18\x02 \x01(\t\"-\n\rTaskResultSet\x12\x1c\n\x07results\x18\x01 \x03(\x0b\x32\x0b.TaskResult\"\xa8\x01\n\nTaskResult\x12\x10\n\x08\x63lass_id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08track_id\x18\x03 \x01(\x05\x12\x12\n\nconfidence\x18\x04 \x01(\x01\x12\x11\n\x03\x62ox\x18\x05 \x01(\x0b\x32\x04.Box\x12\x1b\n\x08segments\x18\x06 \x01(\x0b\x32\t.Segments\x12\x15\n\x05speed\x18\x07 \x01(\x0b\x32\x06.Speed\x12\r\n\x05shape\x18\x08 \x03(\x05\"e\n\x03\x42ox\x12\n\n\x02x1\x18\x01 \x01(\x01\x12\n\n\x02x2\x18\x02 \x01(\x01\x12\n\n\x02y1\x18\x03 \x01(\x01\x12\n\n\x02y2\x18\x04 \x01(\x01\x12\n\n\x02x3\x18\x05 \x01(\x01\x12\n\n\x02x4\x18\x06 \x01(\x01\x12\n\n\x02y3\x18\x07 \x01(\x01\x12\n\n\x02y4\x18\x08 \x01(\x01\" \n\x08Segments\x12\t\n\x01x\x18\x01 \x03(\x01\x12\t\n\x01y\x18\x02 \x03(\x01\"C\n\x05Speed\x12\x11\n\tinference\x18\x01 \x01(\x01\x12\x13\n\x0bpostprocess\x18\x02 \x01(\x01\x12\x12\n\npreprocess\x18\x03 \x01(\x01\x32>\n\x0bTaskService\x12/\n\rStreamResults\x12\x0c.TaskRequest\x1a\x0e.TaskResultSet0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inferencetask_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TASKREQUEST']._serialized_start=23
  _globals['_TASKREQUEST']._serialized_end=71
  _globals['_TASKRESULTSET']._serialized_start=73
  _globals['_TASKRESULTSET']._serialized_end=118
  _globals['_TASKRESULT']._serialized_start=121
  _globals['_TASKRESULT']._serialized_end=289
  _globals['_BOX']._serialized_start=291
  _globals['_BOX']._serialized_end=392
  _globals['_SEGMENTS']._serialized_start=394
  _globals['_SEGMENTS']._serialized_end=426
  _globals['_SPEED']._serialized_start=428
  _globals['_SPEED']._serialized_end=495
  _globals['_TASKSERVICE']._serialized_start=497
  _globals['_TASKSERVICE']._serialized_end=559
# @@protoc_insertion_point(module_scope)
